[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "QES"
authors = [{name = "Fabien Margairaz", email = "fabien.margairaz@utah.edu"}]
dynamic = ["version", "description"]
